baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
logo = "i/logo.svg"

# Css Plugins
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"

# JS Plugins
[[params.plugins.js]]
link = "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/jquery-easy-scroll/jquery.easeScroll.js"

[taxonomies]
  category = "categories"
  drinkscategory = "drinkscategories"

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6
