baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
logo = "i/logo.svg"

# Css Plugins
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"

# JS Plugins
[[params.plugins.js]]
link = "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/mixitup/mixitup.min.js"

[taxonomies]
  category = "categories"
  drinkscategory = "drinkscategories"

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    weight            = 1

  [[menu.main]]
    name              = "Le nostre birre"
    identifier        = "le-nostre-birre"
    url               = "/le-nostre-birre/"
    weight            = 2

  [[menu.main]]
    name              = "Altre bevande"
    identifier        = "alte-bevande"
    url               = "/alte-bevande/"
    weight            = 3

  [[menu.main]]
    name              = "Servizi"
    identifier        = "services"
    url               = "/servizi/"
    weight            = 5

  [[menu.main]]
    name              = "Chi siamo"
    identifier        = "about"
    url               = "/chi-siamo/"
    weight            = 6

  [[menu.main]]
    name              = "Contatti"
    identifier        = "contacts"
    url               = "/contatti/"
    weight            = 7
