backend:
  name: git-gateway
  branch: master

media_folder: "static/i"
publick_folder: "uploads"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Site settings"
        name: "another_settings"
        file: "config.toml"
        fields: 
          - label: "Params"
            name: "params"
            widget: "object"
            fields:
            - {label: "Facebook", name: "facebook", widget: "string"}
            - {label: "Instagram", name: "instagram", widget: "string"}
            - {label: "Email", name: "email", widget: "string"}
            - {label: "Phone", name: "phone", widget: "string"}
            - {label: "Phone clear", name: "phone_clear", widget: "string"}
            - {label: "Logo", name: "logo", widget: "image"}
            - label: "Partners"
              name: "partners"
              widget: "object"
              fields:
              - {label: "Partner 1 image", name: "partner_1_img ", widget: "image"}
              - {label: "Partner 2 image", name: "partner_2_img ", widget: "image"}
              - {label: "Partner 3 image", name: "partner_3_img ", widget: "image"}
            - label: "Footer"
              name: "footer"
              widget: "object"
              fields:
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Hours", name: "hours", widget: "string"}
              - {label: "Hours saturday", name: "hours_saturday", widget: "string"}
              - {label: "Map", name: "map", widget: "string"}
              - {label: "Privacy", name: "privacy", widget: "markdown"}

  - label: "Alte bevande"
    name: "alte-bevande"
    folder: "content/alte-bevande"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
  - label: "Chi-siamo"
    name: "chi-siamo"
    folder: "content/chi-siamo"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "First block", name: "image", widget: "markdown"}
  - label: "Servizi"
    name: "servizi"
    folder: "content/servizi"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "markdown"}
