backend:
  name: git-gateway
  branch: master

media_folder: "static/i"
public_folder: "/i"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Site settings"
        name: "another_settings"
        file: "config.toml"
        fields:
          - label: "Params"
            name: "params"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Phone clear", name: "phone_clear", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - label: "Partners"
                name: "partners"
                widget: "object"
                fields:
                  - {label: "Partner 1 image", name: "partner_1_img ", widget: "image"}
                  - {label: "Partner 2 image", name: "partner_2_img ", widget: "image"}
                  - {label: "Partner 3 image", name: "partner_3_img ", widget: "image"}
              - label: "Footer"
                name: "footer"
                widget: "object"
                fields:
                  - {label: "Address", name: "address", widget: "string"}
                  - {label: "Hours", name: "hours", widget: "string"}
                  - {label: "Hours saturday", name: "hours_saturday", widget: "string"}
                  - {label: "Map", name: "map", widget: "string"}
                  - {label: "Privacy", name: "privacy", widget: "markdown"}

  - label: "Pages"
    name: "content"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Intro title", name: "introTitle", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}
          - {label: "Intro text", name: "introText", widget: "string"}
          - {label: "Intro image", name: "introImg", widget: "image"}
          - {label: "Intro btn text", name: "introBtnText", widget: "string"}
          - {label: "Our beers title", name: "ourBeersSectionTitle", widget: "string"}
          - {label: "Our beers text", name: "ourBeersSectionText", widget: "string"}
          - {label: "Our beers btn text", name: "ourBeersSectionBtnText", widget: "string"}
          - {label: "Our beers image bg", name: "ourBeersSectionImageBg", widget: "image"}
          - {label: "Our beers image", name: "ourBeersSectionImage", widget: "image"}
      - label: "Le nostre birre"
        name: "le-nostre-birre"
        file: "content/le-nostre-birre/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}
      - label: "Alte bevande"
        name: "alte-bevande"
        file: "content/alte-bevande/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}
      - label: "Servizi"
        name: "servizi"
        file: "content/servizi/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}
      - label: "Chi siamo"
        name: "chisiamo"
        file: "content/chi-siamo/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "First block"
            name: "firstBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "markdown"}
          - label: "Second block"
            name: "secondBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "markdown"}
          - label: "Third block"
            name: "thirdBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
      - label: "Contatti"
        name: "contatti"
        file: "content/contatti/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Slug", name: "slug", widget: "string"}

  - label: "Alte bevande"
    name: "alte-bevande"
    folder: "content/alte-bevande"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Link to site", name: "linksToSite", widget: "string"}
      - {
        label: "Category",
        name: "drinkscategories",
        collection: "drinkscategories",
        searchFields: ["slug"],
        valueField: "slug",
        displayFields: ["title"],
        multiple: true,
        widget: "relation"
      }
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Draft", name: "draft", widget: "string", default: false}
  - label: "Le nostre birre"
    name: "le-nostre-birre"
    folder: "content/le-nostre-birre"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Link tex", name: "linkText", widget: "string", required: false}
      - label: "Files"
        name: "fileslist"
        create: true
        widget: "list"
        fields:
          - {label: "File", name: "file", widget: "file"}
          - {label: "FileName", name: "filename", widget: "string"}
  - label: "Chi-siamo"
    name: "chi-siamo"
    folder: "content/chi-siamo"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "First block", name: "image", widget: "markdown"}
  - label: "Servizi"
    name: "servizi"
    folder: "content/servizi"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}

  - label: "Drinks categories"
    name: "drinkscategories"
    create: true
    folder: "content/drinkscategories"
    path: "content/drinkscategories/{{ slug }}"
    media_folder: '/static/i'
    public_folder: '/i'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image for blocks", name: "imageForBlocks", widget: "image"}
      - {
        label: "Image for filter",
        name: "imageForFilter",
        widget: "image",
      }

